version: "3.8"

services:
  nginx_server:
    image: nginx:1.27
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    # network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./dist:/react-app/dist
  
